version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - "echo install: `date`"
      - npm install -g yarn
  
  pre_build:
    commands:
      - "echo pre_build: `date`"
      - yarn install
  
  build:
    commands:
      - "echo build: `date`"
      - yarn run stage

artifacts:
  files: '**/*'
  base-directory: dist